ide:
  image: quay.io/webcenter/docker-emberjs
  volumes:
    - ./home:/home/dev
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY
  ports:
    - "8081:8080"

shell:
  image: quay.io/webcenter/docker-emberjs
  volumes:
    - ./home:/home/dev
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY
  command: xfce4-terminal --command '/bin/bash' --title 'Node Shell'
  privileged: true
  ports:
    - "4200:4200"

shellEmber:
  image: quay.io/webcenter/docker-emberjs
  volumes:
    - ./home:/home/dev
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
  environment:
    - DISPLAY
  command: xfce4-terminal --command '/bin/bash' --title 'Ember Shell'
  privileged: true
